export { Hero } from './Hero'
export { Celebration } from './Celebration'
export { Gallery } from './Gallery'
export { Menus } from './Menus'
export { Testimonials } from './Testimonials'
export { Reels } from './Reels'
export { CtaBlock } from './CtaBlock'
